services:
  # server:
  #   container_name: server
  #   restart: always
  #   build:
  #     context: ../server/
  #     dockerfile: ../server/Dockerfile
  #   image: docker.io/nguyentungson/gr3:${TAGS}
  #   user: "node"
  #   depends_on:
  #     postgres:
  #       condition: service_started
  #   env_file:
  #     - ./backend/.backend.env
  #   networks:
  #     - server-db
  #     - server-redis
  #   ports:
  #     - ${PORT}:${PORT}
  #   healthcheck:
  #     test: wget --quiet --tries=1 --spider http://localhost:${PORT}/healthcheck || exit 1z
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - ./postgresql/.postgresql.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tungsontk3 -d chatdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
